/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vadim_android_NativeMediaPlayerEventListener */

#ifndef _Included_com_vadim_android_NativeMediaPlayerEventListener
#define _Included_com_vadim_android_NativeMediaPlayerEventListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onFinished
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onFinished
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onStarted
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onStarted
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onError
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onError
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onBuffering
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onBuffering
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onPause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onPause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onPrepared
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onPrepared
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_vadim_android_NativeMediaPlayerEventListener
 * Method:    onVideoSizeChanged
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeMediaPlayerEventListener_onVideoSizeChanged
  (JNIEnv *, jclass, jlong, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
