/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vadim_android_NativeSurfaceChangeListener */

#ifndef _Included_com_vadim_android_NativeSurfaceChangeListener
#define _Included_com_vadim_android_NativeSurfaceChangeListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vadim_android_NativeSurfaceChangeListener
 * Method:    onSurfaceChanged
 * Signature: (JLandroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_vadim_android_NativeSurfaceChangeListener_onSurfaceChanged
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
